Updates to github org/repo names
adoptium/build-jdk pull request #33
Opened 2021-05-21 15:26 UTC by smlambert

Fixes #32 

Signed-off-by: Shelley Lambert <slambert@gmail.com>

2021-05-21 15:29 UTC, smlambert commented
Noting that I left some reference to AdoptOpenJDK as this action needs to go and download some utilities to set up environment properly and those are currently hosted on the existing Jenkins server, and a bootJDK from the old API for jdk10 releases (which will not be served from new API, I presume).  If I update those references, this github action will be broken.

2021-05-21 17:43 UTC, karianna requested changes
nitpick

2021-05-21 17:43 UTC, karianna commented on SECURITY.md
> +Please report vulnerabilities to [security@adoptium.net](security@adoptium.net).
I changed this to be TBD in the other repo as its not set up yet

2021-05-21 17:44 UTC, karianna commented
> Noting that I left some reference to AdoptOpenJDK as this action needs to go and download some utilities to set up environment properly and those are currently hosted on the existing Jenkins server, and a bootJDK from the old API for jdk10 releases (which will not be served from new API, I presume). If I update those references, this github action will be broken.

Can we cache those things locally / on a different host?  We could in theory even host on adoptium.net website...

2021-05-22 20:16 UTC, smlambert commented
I presume we will build them on the 'new Jenkins server' with its new domain name, at which point we can do a 2nd PR in this repo.  But we can discuss in PMC meeting.

2021-05-25 20:13 UTC, sophia-guo approved these changes

2021-05-25 20:57 UTC, karianna approved these changes

2021-05-26 13:04 UTC, merged